---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 882558666-JcnSMZWeHIHwxCnStL9QZyZkF80PdmF9FE3ZFIbX
:access_token_secret: IeCMNm3K1K5IRgBBPFknsbWrV8hTuLys60K6L18Tqie5Z
